language: node_js

node_js:
  - "stable"

sudo: false

before_script:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer show -i

script:
  - npm run lint
  - npm test
  - npm run test-node
