language: node_js

node_js:
  - "stable"

sudo: false

before_script:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com 750f096e73bd29bd191ec553398a825f5836f726; fi;
  - composer show -i

script:
  - npm run lint
  - npm test
  - npm run test-node
